version: "3.8"

services:
  frontend:
    build: ./client
    ports:
      - 3000:3000

  backend:
    build: ./server
    ports:
      - 3001:3001
      
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: