version: "3.8"
services:
  backend:
    restart: always
    build: ./server
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/mongodb
      DB_NAME: my_db
    depends_on:
      - mongo

  frontend:
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: {}
